before_script:
  - npm install -g hackmyresume
script: hackmyresume build resume.json TO out/index.html -t positive
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  local_dir: out